### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gastaldi**
Fixed minor typo

### CODE REVIEW

**Comment by rhuss** [comment]
merge

**Comment by rhuss** [comment]
test this please

**Comment by jimmidyson** [comment]
@rhuss It's running! I'd just restarted Jenkins after some plugin updates - sorry... Now be patient ;)

**Comment by rhuss** [comment]
@jimmidyson that is the "please" for ;) 

Just kidding, afaik "test this please" is a trigger for [firing up a test](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin) when not on the whitelist. Ok, should have been "ok to test" probably ...

**Comment by jimmidyson** [comment]
Either should work iirc

**Pull request merged**
